services:
  opensearch:
    container_name: opensearch
    environment:
      cluster.name: opensearch-paradrop-cluster
      node.name: opensearch-node1
      bootstrap.memory_lock: true
      discovery.type: single-node
      http.cors.enabled: "false"
      http.compression: "false"
      network.host: 0.0.0.0
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "dtYe2cKY2YtyBEJ49a"
      # OPENSEARCH_JAVA_OPTS: "-Xms4g -Xmx12g"
    image: opensearchproject/opensearch:2.13.0
    networks:
      - paradrop
    ports:
      - 127.0.0.1:9200:9200
    restart: unless-stopped
    volumes:
      - ./elk/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml:rw

  opensearch_dashboards:
    container_name: opensearch_dashboards
    depends_on:
      opensearch:
        condition: service_started
    environment:
      SERVER_HOST: 0.0.0.0
    image: opensearchproject/opensearch-dashboards:2.13.0
    networks:
      - paradrop
    ports:
      - 127.0.0.1:5601:5601
    restart: unless-stopped
    volumes:
      - ./elk/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro

  api:
    build:
      context: ./api
    container_name: paradrop_api
    depends_on:
      opensearch:
        condition: service_started
    networks:
      - paradrop
    ports:
      - 127.0.0.1:5000:5000
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      args:
        - URL
    container_name: paradrop_ui
    depends_on:
      api:
        condition: service_started
      opensearch:
        condition: service_started
    networks:
      - paradrop
    ports:
      - 8443:8443
    restart: unless-stopped

  docs:
    build:
      context: ./docs
    container_name: paradrop_docs
    depends_on:
      ui:
        condition: service_started
    networks:
      - paradrop
    ports:
      - 127.0.0.1:3008:3008
    restart: unless-stopped

networks:
  paradrop:
    driver: bridge
